# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: match_api/v1/match.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.const
import grpclib.client
if typing.TYPE_CHECKING:
    import grpclib.server

import match_api.v1.match_pb2


class MatchServiceBase(abc.ABC):

    @abc.abstractmethod
    async def Health(self, stream: 'grpclib.server.Stream[match_api.v1.match_pb2.HealthRequest, match_api.v1.match_pb2.HealthResponse]') -> None:
        pass

    @abc.abstractmethod
    async def HandleLike(self, stream: 'grpclib.server.Stream[match_api.v1.match_pb2.HandleLikeRequest, match_api.v1.match_pb2.HandleLikeResponse]') -> None:
        pass

    @abc.abstractmethod
    async def HandleSkip(self, stream: 'grpclib.server.Stream[match_api.v1.match_pb2.HandleSkipRequest, match_api.v1.match_pb2.HandleSkipResponse]') -> None:
        pass

    @abc.abstractmethod
    async def ListUserMatches(self, stream: 'grpclib.server.Stream[match_api.v1.match_pb2.ListUserMatchesRequest, match_api.v1.match_pb2.ListUserMatchesResponse]') -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            '/match_api.v1.MatchService/Health': grpclib.const.Handler(
                self.Health,
                grpclib.const.Cardinality.UNARY_UNARY,
                match_api.v1.match_pb2.HealthRequest,
                match_api.v1.match_pb2.HealthResponse,
            ),
            '/match_api.v1.MatchService/HandleLike': grpclib.const.Handler(
                self.HandleLike,
                grpclib.const.Cardinality.UNARY_UNARY,
                match_api.v1.match_pb2.HandleLikeRequest,
                match_api.v1.match_pb2.HandleLikeResponse,
            ),
            '/match_api.v1.MatchService/HandleSkip': grpclib.const.Handler(
                self.HandleSkip,
                grpclib.const.Cardinality.UNARY_UNARY,
                match_api.v1.match_pb2.HandleSkipRequest,
                match_api.v1.match_pb2.HandleSkipResponse,
            ),
            '/match_api.v1.MatchService/ListUserMatches': grpclib.const.Handler(
                self.ListUserMatches,
                grpclib.const.Cardinality.UNARY_UNARY,
                match_api.v1.match_pb2.ListUserMatchesRequest,
                match_api.v1.match_pb2.ListUserMatchesResponse,
            ),
        }


class MatchServiceStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.Health = grpclib.client.UnaryUnaryMethod(
            channel,
            '/match_api.v1.MatchService/Health',
            match_api.v1.match_pb2.HealthRequest,
            match_api.v1.match_pb2.HealthResponse,
        )
        self.HandleLike = grpclib.client.UnaryUnaryMethod(
            channel,
            '/match_api.v1.MatchService/HandleLike',
            match_api.v1.match_pb2.HandleLikeRequest,
            match_api.v1.match_pb2.HandleLikeResponse,
        )
        self.HandleSkip = grpclib.client.UnaryUnaryMethod(
            channel,
            '/match_api.v1.MatchService/HandleSkip',
            match_api.v1.match_pb2.HandleSkipRequest,
            match_api.v1.match_pb2.HandleSkipResponse,
        )
        self.ListUserMatches = grpclib.client.UnaryUnaryMethod(
            channel,
            '/match_api.v1.MatchService/ListUserMatches',
            match_api.v1.match_pb2.ListUserMatchesRequest,
            match_api.v1.match_pb2.ListUserMatchesResponse,
        )
