"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class HealthRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___HealthRequest: typing_extensions.TypeAlias = HealthRequest

@typing.final
class HealthResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OK_FIELD_NUMBER: builtins.int
    ok: builtins.bool
    def __init__(
        self,
        *,
        ok: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["ok", b"ok"]) -> None: ...

Global___HealthResponse: typing_extensions.TypeAlias = HealthResponse

@typing.final
class HandleLikeRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    LIKER_ID_FIELD_NUMBER: builtins.int
    LIKED_ID_FIELD_NUMBER: builtins.int
    liker_id: builtins.int
    liked_id: builtins.int
    def __init__(
        self,
        *,
        liker_id: builtins.int = ...,
        liked_id: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["liked_id", b"liked_id", "liker_id", b"liker_id"]) -> None: ...

Global___HandleLikeRequest: typing_extensions.TypeAlias = HandleLikeRequest

@typing.final
class HandleLikeResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MATCHED_FIELD_NUMBER: builtins.int
    MATCH_ID_FIELD_NUMBER: builtins.int
    matched: builtins.bool
    match_id: builtins.int
    def __init__(
        self,
        *,
        matched: builtins.bool = ...,
        match_id: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_match_id", b"_match_id", "match_id", b"match_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_match_id", b"_match_id", "match_id", b"match_id", "matched", b"matched"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_match_id", b"_match_id"]) -> typing.Literal["match_id"] | None: ...

Global___HandleLikeResponse: typing_extensions.TypeAlias = HandleLikeResponse

@typing.final
class HandleSkipRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ACTOR_ID_FIELD_NUMBER: builtins.int
    TARGET_ID_FIELD_NUMBER: builtins.int
    actor_id: builtins.int
    target_id: builtins.int
    def __init__(
        self,
        *,
        actor_id: builtins.int = ...,
        target_id: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["actor_id", b"actor_id", "target_id", b"target_id"]) -> None: ...

Global___HandleSkipRequest: typing_extensions.TypeAlias = HandleSkipRequest

@typing.final
class HandleSkipResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: builtins.int
    success: builtins.bool
    def __init__(
        self,
        *,
        success: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["success", b"success"]) -> None: ...

Global___HandleSkipResponse: typing_extensions.TypeAlias = HandleSkipResponse
