# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: match_api/v1/match.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'match_api/v1/match.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18match_api/v1/match.proto\x12\x0cmatch_api.v1\"\x0f\n\rHealthRequest\"\x1c\n\x0eHealthResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\"7\n\x11HandleLikeRequest\x12\x10\n\x08liker_id\x18\x01 \x01(\x03\x12\x10\n\x08liked_id\x18\x02 \x01(\x03\"I\n\x12HandleLikeResponse\x12\x0f\n\x07matched\x18\x01 \x01(\x08\x12\x15\n\x08match_id\x18\x02 \x01(\x03H\x00\x88\x01\x01\x42\x0b\n\t_match_id\"8\n\x11HandleSkipRequest\x12\x10\n\x08\x61\x63tor_id\x18\x01 \x01(\x03\x12\x11\n\ttarget_id\x18\x02 \x01(\x03\"%\n\x12HandleSkipResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xf5\x01\n\x0cMatchService\x12\x43\n\x06Health\x12\x1b.match_api.v1.HealthRequest\x1a\x1c.match_api.v1.HealthResponse\x12O\n\nHandleLike\x12\x1f.match_api.v1.HandleLikeRequest\x1a .match_api.v1.HandleLikeResponse\x12O\n\nHandleSkip\x12\x1f.match_api.v1.HandleSkipRequest\x1a .match_api.v1.HandleSkipResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'match_api.v1.match_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HEALTHREQUEST']._serialized_start=42
  _globals['_HEALTHREQUEST']._serialized_end=57
  _globals['_HEALTHRESPONSE']._serialized_start=59
  _globals['_HEALTHRESPONSE']._serialized_end=87
  _globals['_HANDLELIKEREQUEST']._serialized_start=89
  _globals['_HANDLELIKEREQUEST']._serialized_end=144
  _globals['_HANDLELIKERESPONSE']._serialized_start=146
  _globals['_HANDLELIKERESPONSE']._serialized_end=219
  _globals['_HANDLESKIPREQUEST']._serialized_start=221
  _globals['_HANDLESKIPREQUEST']._serialized_end=277
  _globals['_HANDLESKIPRESPONSE']._serialized_start=279
  _globals['_HANDLESKIPRESPONSE']._serialized_end=316
  _globals['_MATCHSERVICE']._serialized_start=319
  _globals['_MATCHSERVICE']._serialized_end=564
# @@protoc_insertion_point(module_scope)
