from match_service.adapters.interaction_staging.postgres.adapter import PostgresInteractionStagingRepositoryAdapter as PostgresInteractionStagingRepositoryAdapter
from match_service.adapters.like.postgres.adapter import PostgresLikeRepositoryAdapter as PostgresLikeRepositoryAdapter
from match_service.adapters.match.postgres.adapter import PostgresMatchRepositoryAdapter as PostgresMatchRepositoryAdapter
from match_service.adapters.outbox.postgres.adapter import PostgresOutboxRepositoryAdapter as PostgresOutboxRepositoryAdapter
